### PR TITLE
Iron Irwini support

### PR DESCRIPTION
**Pull request by ted-miller**
- Add project infrastructure
- Remove remap rules
- Update documentation

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Honestly, I'm hesitant to approve this as it basically breaks existing functionality.

I agree with your [comment ](https://github.com/Yaskawa-Global/motoros2/issues/52#issuecomment-2334647081) that we should support Iron already, but remaps do see use.

I'm not sure whether having Iron supported without remapping is a good idea.

But I won't block it if you really want to merge it in.

(I would recommend rebasing though, instead of merging in `main`)

**Comment by ted-miller** [comment]
This passes all my testing.

**Comment by ted-miller** [comment]
Since Iron Irwini is EOL in a month, we will skip this release and focus on Jazzy, which is LTS.

**Comment by ted-miller** [comment]
NOTE: The work in `iron_wip` will be carried forward into the jazzy release

**Comment by gavanderhoorn** [comment]
@jimmy-mcelwain @ted-miller: the `strtoll(..)` implementation -- if really needed -- should ideally go into the posix shim. Not in MotoROS2 itself.

**Pull request closed without merging**
