### PR TITLE
Switch to `clock_gettime(..)`

### LINKED ISSUE #91: Implicit declaration of `gettimeofday(..)`
#61 introduced usage of `gettimeofday(..)` here (discussed in https://github.com/Yaskawa-Global/motoros2/pull/61#issuecomment-1629586970):

https://github.com/Yaskawa-Global/motoros2/blob/9fe8cf237f38c79b76ffb57ab111522ffb80d217/src/Debug.c#L69

this is not a function supported/exposed by the M+ SDK, so the M+ compiler complains about an *implicit declaration*:

> ```
> Debug.c(69): warning : implicit declaration of function 'gettimeofday'
> ```

For YRC, builds will work as `gettimeofday(..)` is present on the controller, but other controllers may not have this function causing the `.out` to not load. DX2 fi doesn't appear to support it (https://github.com/Yaskawa-Global/motoros2/issues/18#issuecomment-1629317081).

Regardless, the warning should be addressed (as it's really an error).

### PR DESCRIPTION
**Pull request by gavanderhoorn**
Fixes #91 (well .. avoids it by just not using `gettimeofday(..)`).

Tested on my YRC.

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
@SejalBehere: could you maybe also take a look?

**Review by ted-miller — APPROVED** [review]
@SejalBehere ran a successful test too. It looks good.

**Comment by SejalBehere** [comment]
I tested this and it worked perfectly without any warnings. The timestamp was obtained as folows:

[1689367678.58081555] [192.168.1.31:58228]: FRI 2023-07-14 16:47:55.767 Ros_ServiceResetError_Initialize(..):svc_reset_error_init: memory free: 992728 bytes, delta: -280 
[1689367678.58549786] [192.168.1.31:58228]: FRI 2023-07-14 16:47:55.772 Ros_ServiceStartTrajMode_Initialize(..):svc_start_traj_mode_init: memory free: 992432 bytes, delta: -296
[1689367678.58938360] [192.168.1.31:58228]: FRI 2023-07-14 16:47:55.776 Ros_ServiceStartPointQueueMode_Initialize(..):svc_start_point_queue_mode_init: memory free: 992136 bytes, delta: -296
[1689367678.59277368] [192.168.1.31:58228]: FRI 2023-07-14 16:47:55.779 Ros_ServiceStopTrajMode_Initialize(..):svc_stop_traj_mode_init: memory free: 991848 bytes, delta: -288
[1689367678.59655929] [192.168.1.31:58228]: FRI 2023-07-14 16:47:55.783 Ros_ServiceSelectMotionTool_Initialize(..):svc_select_tool_init: memory free: 991552 bytes, delta: -296

**Comment by gavanderhoorn** [comment]
Off-topic, but: do you always see timestamps like `[1689367678.58081555]`?

For me it formats them as a human readable time:

```
[2023-07-14 14:42:07.146661]
```

**Comment by SejalBehere** [comment]
No. For me the format always goes as [time_msg_rcvd] [ip:port] msg

The time in the initial position is shown like this [1689367678.58081555] but then I am also shown the timestamp in human readable form before the debug msg.

**[1689367678.58081555]** [192.168.1.31:58228]: **FRI 2023-07-14 16:47:55.767** Ros_ServiceResetError_Initialize(..):svc_reset_error_init: memory free: 992728 bytes, delta: -280

**Comment by ted-miller** [comment]
> Off-topic, but: do you always see timestamps like [1689367678.58081555]?

Looks like that is my fault. I haven't updated my listening script in a _long_ time. 

I've still got `print(f'[{stamp_recvd:.8f}]: {msg}')`. 

That was one of the main motivations for this PR in the first place. But oh well, I still think this is valuable.

**Pull request merged**
