### PR TITLE
Release `0.1.1`

### PR DESCRIPTION
**Pull request by gavanderhoorn**
As per subject.

This updates the relevant files to reflect the release of `0.1.1`.

Please only review, or if you want to merge, use a *rebase merge*.

I'll push the tag and draft the actual release later.

### CODE REVIEW

**Review by ted-miller — APPROVED** [review]

**Comment by ted-miller** [comment]
Looks good to me.

**Comment by gavanderhoorn** [comment]
I've posted a *draft* release [here](https://github.com/Yaskawa-Global/motoros2/releases) @ted-miller.

Please take a look.

**Comment by ted-miller** [comment]
Evertyhing looks good for this release. Going forward, I think we should reformat the table for `Supported versions of ROS 2`. It'll get rather overwhelming if we add more flavors or ROS2 and/or the FS100.

**Comment by ted-miller** [comment]
Thanks for taking care of the release!

Do you think it's worth announcing DX2 support on discourse?

**Comment by gavanderhoorn** [comment]
> Do you think it's worth announcing DX2 support on discourse?

Yes, that's a good idea.

Will you post it? Might even deserve its own post, instead of a comment on the initial MotoROS2 announcement.

**Comment by ted-miller** [comment]
Will do.

**Pull request merged**
